// const moviesModel = require("../models/currentmovies");
var express = require('express');
var router = express.Router();
const moviesModule = require('../module/moviesModule');
const bookingsModule = require('../module/bookingsModule');
var ceatsModule = require("../module/ceatsModule");
router.get("/movieceats/:bookingdate/:moviename",moviesModule.getmovieceats);
router.get("/getceats/:moviename/:show/:bookingdate",moviesModule.getCeats);
router.post("/postmovies",moviesModule.addMovie);
router.put("/editmovie",moviesModule.editMovie);
router.post("/bookings",bookingsModule.postbookings);
router.get("/getbookings/:bookingdate/:username",bookingsModule.getbookings);
router.get("/getbookings/:email",bookingsModule.getUserbookings);
router.get("/feedback",bookingsModule.getFeedback);
router.get("/getuserbookings/:moviename",bookingsModule.getBookingsByMovieName);
router.post("/ceats",ceatsModule.postceats);
router.get('/getallmovies',moviesModule.getAllMovies);
router.get('/getmovies/:id',moviesModule.getMovies);
router.get('/getmovie/:id',moviesModule.getMovie);
router.get('/getshows/:id',moviesModule.getShows);
router.delete('/deletemovie/:id',moviesModule.deleteMovie);
router.get("/searchmovies/:name",moviesModule.searchByName);
module.exports = router;